#!/usr/bin/lua5.1

local theme = require('theme')
local bar = require('lua.bar-theme')
local client = require('lua.client-theme')

local home = os.getenv("HOME")


local theme_current = theme.get_theme_value()

-- the file structure looks something like this
-- .
-- ├── config
-- ├── modules
-- │   ├── bar.conf <-- generated by sway-theme
-- │   └── theme.conf <-- generated by sway-theme
-- ├── statusBar
-- └── sway-theme.lua
local make_bar_theme = function(config)
  local file_path = home .. "/.config/sway/modules/bar.conf"
  local file = io.open(file_path, "w")

  if file then
    if theme_current == "light" then
      file:write(string.format(config))
    else
      file:write(string.format(config))
    end
    file:close()
  else
    print("Failed to write to file: " .. file_path)
    os.exit(1)
  end
end

local make_client_theme = function(config)
  local file_path = home .. "/.config/sway/modules/theme.conf"
  local file = io.open(file_path, "w")

  if file then
    if theme_current == "light" then
      file:write(config)
    else
      file:write(config)
    end
    file:close()
  else
    print("Failed to write to file: " .. file_path)
    os.exit(1)
  end
end

make_bar_theme(bar.get_bar_config())
make_client_theme(client.get_client_config())
