local theme = require('theme')

local c = theme.get_colors()

local M = {}

local clientTheme = [[
# DO NOT EDIT THIS FILE
# This file is generated by %s
# Please edit this file instead to change the bar configuration

set $bg             %s
set $bg-inactive    %s
set $bg-urgent      %s
set $text-light     %s
set $text-dark      %s
set $text-inactive  %s

# set color theme
# class                 border        bground       text            indicator     child_border
client.focused          $bg           $bg           $text-dark      $bg           $bg
client.focused_inactive $bg-inactive  $bg-inactive  $text-inactive  $bg-inactive  $bg-inactive
client.unfocused        $bg-inactive  $bg-inactive  $text-inactive  $bg-inactive  $bg-inactive
client.urgent           $bg-urgent    $bg-urgent    $text-light     $bg-urgent    $bg-urgent
client.placeholder      $bg-inactive  $bg-inactive  $text-inactive  $bg-inactive  $bg-inactive
]]

local clientThemeLight = string.format(
  clientTheme,
  arg[0],
  c.base2,
  c.base1,
  c.accent1,
  c.accent1,
  c.accent2,
  c.accent1
)

local clientThemeDark = string.format(
  clientTheme,
  arg[0],
  c.accent1,
  c.base1,
  c.accent1,
  c.accent1,
  c.base2,
  c.base2
)

M.get_client_config = function()
  local theme_current = theme.get_theme_value()
  if theme_current == "light" then
    return clientThemeLight
  else
    return clientThemeDark
  end
end

return M
