restic_backup_dir: /home/roland/.restic
restic_secrets_path: /home/roland/.restic/secrets
restic_backup_shell_script_path: /usr/local/bin/restic-backup.sh
restic_backup_targets: '/home /etc /opt /root /usr'
restic_exclude_file: /home/roland/.config/restic/exclude
aws_s3_url: 's3:https://minio.wiredcrop.net/'
# bucket_name: restic-archive-debian
