# Inserts a blank line between shell prompts
add_newline = false

# WIP LIGHT THEME
# TODO create a dark theme with color1, color2 etc that use the current default theme colors
# TODO will need to take screenshots and extract the colors to use them in the theme

# format prompt
# format = "$directory$character(color1)"
format = "$directory$character(color1)"

# TODO part of light/dark theme - change this later
palette = 'dark'

[palettes.dark]
# basic prompt
color1 = '#FFFFFF' # white
# quotes
color2 = '#F0C674' # yellow
# incorrect command
color3 = '#CC6666' # red
# cursor prompt, and correct command
color4 = '#B5BD68' # green
# directory
color5 = '#8ABEB7' # cyan


[palettes.light]
color1 = '#000000'
color2 = '#F5C936'
color3 = '#CC6666'
# color4 = '#3B8239'
color4 = '#000000'
# color5 = '#5A5598'
color5 = '#000000'

# configure directory module
[directory]
truncation_length = 8
truncate_to_repo = true
style = 'bold color5'

[character]
success_symbol = '[❯](color4)'
error_symbol = '[❯](color3)'

# this only show up when in SSH (ssh_only)
[hostname]
ssh_only = true
format = "[$hostname](red) "

# this only show up when in SSH (show_always)
[username]
style_user = "yellow"
format = "[$user]($style)[@](blue)"
show_always = false

# Disable all packages for things i use
[golang]
disabled = true

[ruby]
disabled = true

[nodejs]
disabled = true

[lua]
disabled = true

# disable package versions
[package]
disabled = true
