# after changing this file, reload the agent with:
# gpgconf --kill gpg-agent
# optionally pick between a GUI and TERMINAL version of GNUPG pin entry
#
# pinentry-program /usr/bin/pinentry-curses
# pinentry-program /usr/bin/pinentry-qt
pinentry-program /home/roland/.local/scripts/pinentry-wofi
default-cache-ttl 3600
max-cache-ttl 3600
