#! /bin/sh

sxhkd &

bspc monitor LVDS-1 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-2 1 2 3 4 5 6 7 8 9

bspc config border_width         4
bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-center ~/Documents/Pictures/wallpaper.jpg

pulseaudio