#!/bin/bash

while [[ $# -gt 0 ]]; do
	case $1 in
	-w | --word)
		WORD="$2"
		shift 2
		;;
	*) shift ;;
	esac
done

padBorder() {
	# pad the border
	for ((c = 0; c < $1; c++)); do
		echo -ne "$2"
	done
}

# length of the word
STRLEN=$(echo -n $WORD | wc -m)
# space on each side
STRSPACE=$(($STRLEN / "2"))
[[ "$STRSPACE" -gt "5" ]] && STRSPACE=5

# ########################
padBorder $(($STRSPACE + $STRLEN + $STRSPACE)) "#"
printf "\n"

# Dont print the end of the pad border if the string is short
[[ "$STRLEN" -gt "2" ]] && printf "#" || printf ""

padBorder $(($STRSPACE - 1)) " " # space the border out
printf "%s" "$WORD"              # print the word
padBorder $(($STRSPACE - 1)) " " # space the border out

# Dont print the end of the pad border if the string is short
[[ "$STRLEN" -gt "2" ]] && printf "#" || printf ""

printf "\n"
padBorder $(($STRSPACE + $STRLEN + $STRSPACE)) "#"
# ########################

printf "\n"

