#!/usr/bin/lua

-- RIPDRAG WRAPPER
-- Wraps ripdrag for use with lf
-- lf outputs multiple files as $1\n$2...
-- this script converts them to $1 $2, stripping the newline
-- then it calls ripdrag with the corrected arguments

-- Check if at least one argument is provided
if #arg < 1 then
  print("Usage: ripdrag-wrapper <string1> [<string2> <string3> ...]")
  os.exit(1)
end

local function split_by_newlines(str)
  local lines = {}
  for line in string.gmatch(str, "([^\n]*)\n?") do
    if line ~= "" then
      table.insert(lines, line)
    end
  end
  return lines
end

local t = split_by_newlines(arg[1])

-- modify each table entry so its surrounded by quotes
for i, line in ipairs(t) do
  t[i] = "\"" .. line .. "\""
end

local combinedString = table.concat(t, " ")

os.execute("ripdrag " .. combinedString)
