#!/bin/zsh

zparseopts -D -E - -edit=edit_flag -copy=copy_flag -open=open_flag

screenshot_dir=$(mktemp -d)
screenshot_file="$screenshot_dir/screenshot-$(date +%Y%m%d-%H%M%S).png"

# Take a screenshot
grim -g "$(slurp)" "$screenshot_file"
if [[ $? -ne 0 ]]; then
  return 1
fi
echo "$screenshot_file"

# Open the screenshot in GIMP
if [[ -n "$edit_flag" && $(command -v gimp) ]]; then
  gimp "$screenshot_file" >/dev/null 2>&1 &
  return 0
fi

# copy to clipboard
if [[ -n "$copy_flag" ]]; then
  wl-copy < "$screenshot_file"
  return 0
fi

# open in image viewer
if [[ -n "$open_flag" ]]; then
  if [[ $( command -v imv-wayland ) ]]; then
    imv-wayland "$screenshot_file"
    return 0
  fi
  echo "no image viewer installed"
  return 1
  # TODO add some more image viewers here
fi
