#!/usr/bin/lua
local utils = require("script-utils")

if #arg < 1 then
  print('please provide a file as the first argument')
  os.exit(1, true)
end

-- List of valid image extensions
local image_extensions = {
  ".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp"
}

for i = 1, #arg do
  local file_path = arg[i]

  -- if the file is an image then ask the user to either
  -- OPEN, COPY, or EDIT it
  if utils.path_has_extension(file_path, image_extensions) then
    local choice = utils.exec(
      'echo "Preview\\nPreview whole directory\\nCopy\\nEdit" | rofi -dmenu -i -p "Select action"')
    if choice == "Preview" then
      os.execute('imv-wayland "' .. file_path .. '"')
    elseif choice == "Preview whole directory" then
      local dirname = file_path:match("(.*/)")
      print(dirname)
      os.execute('imv-wayland -r ' .. dirname)
    elseif choice == "Copy" then
      os.execute('wl-copy < "' .. file_path .. '" --type image/png')
    elseif choice == "Edit" then
      os.execute('gimp "' .. file_path .. '" &')
    else
      print("No valid choice selected.")
    end
    os.exit(0, true)
  end

  -- open the file with the default file handler
  os.execute("xdg-open " .. file_path)
end
