# export PATH=/usr/bin/pip3:$PATH export LC_ALL="en_US.UTF-8"
export EDITOR=nvim

# when using the mv command include hidden .files
setopt glob_dots

# share zsh command history between terminal sessions/windows
setopt share_history

# run `zkbd` after booting to set your keybinds
if [[ ! -a ~/.zkbd/$TERM-${${DISPLAY:t}:-$VENDOR-$OSTYPE} ]]; then
  autoload zkbd
fi


# load the completions system on $fpath and ignore all insecure files and directories
# insecure = files that dont belong to root or you
autoload compinit -i

# I redefine the wordchars and exclude "/" from it.
# This causes `cd /first/second` C+W to return `cd /first/`
# WORDCHARS='*?_-.[]~=&;!#$%^(){}<>'
WORDCHARS='*?_.[]~=&;!#$%^(){}<>'

# Use a history file to persist history
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory
setopt SHARE_HISTORY

# Import all the things
source ~/.zsh/aliases.zsh
source ~/.zsh/autocomplete.zsh
source ~/.zsh/bindings.zsh
source ~/.zsh/environment.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/plugins.zsh
source ~/.zsh/ssh.zsh
[[ -f ~/.zsh/secrets.zsh ]] && source ~/.zsh/secrets.zsh

eval "$(starship init zsh)"
